name: Notify docs on release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        default: test-dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "hello, tag=${{ inputs.tag }}"
